---
services: docker

env:
  - distro: centos6
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
    debug_ansible:
services:
  - docker

before_install:
  # Pull container
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/ansible-check_oracle_health:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/ansible-check_oracle_health/tests/${playbook} --syntax-check'
  # Install env for check_oracle_health
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm yum install -y epel-release'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm yum install -y nagios-plugins-oracle'
  # Running playbook
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/ansible-check_oracle_health/tests/${playbook} ${debug_ansible}'

  # Test role idempotence.
  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/ansible-check_oracle_health/tests/${playbook} | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=1.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  # Make sure that check_oracle_health still working
  - >
    docker exec "$(cat ${container_id})" perl /usr/lib64/nagios/plugins/check_oracle_health
    && (echo 'check_oracle_health working' && exit 0)
    || (echo 'check_oracle_health not working' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
