---
# tasks file for ansible-check_oracle_health
- include_vars: "{{ ansible_distribution }}.yml"
- include: "{{ ansible_os_family }}.yml"

- name: Fetch oracle_health script
  get_url:
    url: "{{ oracle_health_repo }}"
    dest: /tmp/

- name: Check if Oracle module is installed
  stat:
    path: /usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.so
  register: oracle_perl_module

- name: Check if Check_oracle_health is installed
  stat:
    path: "{{nagios_nrpe_server_plugins_dir}}/{{ oracle_health_name }}"
  register: check_is_installed

- name: Untar oracle health
  unarchive:
    src: "/tmp/{{ oracle_health_name }}.tar.gz"
    dest: "{{nagios_nrpe_server_plugins_dir}}"
    remote_src: True
  when: not check_is_installed.stat.exists

- name: Create SQL monitoring file
  become: yes
  become_user: oracle
  become_method: su
  template:
    src: oracle_monitoring.j2
    dest: /tmp/oracle_monitoring.sql

- name: Import SQL monitoring file
  shell: sqlplus / as sysdba @/tmp/oracle_monitoring.sql

- name: Install from cpan DBD::Oracle
  cpanm:
    name: DBD::Oracle
    system_lib: yes
  when: not oracle_perl_module.stat.exists

- name: Running ./configure for "{{ oracle_health_name }}"
  command: '"{{ item }}" chdir="{{nagios_nrpe_server_plugins_dir}}/{{ oracle_health_name }}"'
  with_items:
    - ./configure
  when: not check_is_installed.stat.exists

- name: Running "make" for "{{ oracle_health_name }}"
  command: '"{{ item }}" chdir="{{nagios_nrpe_server_plugins_dir}}/{{ oracle_health_name }}"'
  with_items:
    - make
  when: not check_is_installed.stat.exists

- name: Running "make install" for "{{ oracle_health_name }}"
  command: 'make install chdir="{{nagios_nrpe_server_plugins_dir}}/{{ oracle_health_name }}"'
  when: not check_is_installed.stat.exists

- name: Create symlink for check_oracle_health
  file:
    src: "{{nagios_nrpe_server_plugins_dir}}/{{ oracle_health_name }}/plugins-scripts/check_oracle_health"
    dest: "{{nagios_nrpe_server_plugins_dir}}/check_oracle_health"
    state: link
    group: nrpe
    owner: nrpe

- name: Get var from oracle user
  slurp:
    src: "{{ oracle_env_path }}"
  register: profile

- name: Define oracle env var
  shell: echo -e "{{ profile['content'] | b64decode }}"
  register: oracle_env

- name: Add environement file to NRPE
  template:
    src: nrpe_env.j2
    dest: /etc/sysconfig/nrpe

- name: Add nrpe to oinstall group
  user:
    name: nrpe
    groups: oinstall
    append: yes