---
# tasks file for ansible-check_oracle_health
- include_vars: "{{ ansible_distribution }}.yml"
- include: "{{ ansible_os_family }}.yml"

- name: Fetch oracle_health script
  get_url:
    url: "{{ oracle_health_repo }}"
    dest: /tmp/

- name: Untar oracle health
  unarchive:
    src: "/tmp/{{ oracle_health_name }}.tar.gz"
    dest: "{{nagios_nrpe_server_plugins_dir}}"
    remote_src: True

- name: Create SQL monitoring file
  template:
    src: oracle_monitoring.j2
    dest: /tmp/oracle_monitoring.sql

- name: Import SQL monitoring file
  shell: sqlplus / as sysdba @/tmp/oracle_monitoring.sql

- name: Install from cpan DBD::Oracle
  cpanm:
    name: DBD::Oracle
    system_lib: yes

- name: Running ./configure for "{{ oracle_health_name }}"
  command: '"{{ item }}" chdir="{{nagios_nrpe_server_plugins_dir}}/{{ oracle_health_name }}"'
  with_items:
    - ./configure

- name: Running "make" for "{{ oracle_health_name }}"
  command: '"{{ item }}" chdir="{{nagios_nrpe_server_plugins_dir}}/{{ oracle_health_name }}"'
  with_items:
    - make

- name: Running "make install" for "{{ oracle_health_name }}"
  command: 'make install chdir="{{nagios_nrpe_server_plugins_dir}}/{{ oracle_health_name }}"'

- name: Get var from oracle user
  slurp:
    src: "{{ oracle_env_path }}"
  register: profile

- name: Define oracle env var
  shell: echo -e "{{ profile['content'] | b64decode }}"
  register: oracle_env

- name: Add env var to NRPE
  lineinfile:
    dest: /etc/sysconfig/nrpe
    line: "{{ oracle_env['stdout'] | replace('export ', '') }}"
    state: present

- name: Register var ORACLE_HOME
  shell: source "{{ oracle_env_path }}" && echo $ORACLE_HOME
  register: oracle_home

- name: Add nrpe to oinstall group
  user:
    name: nrpe
    group: oinstall
    append: yes